### PR TITLE
Add JitPack integration

### PR DESCRIPTION
**Pull request by RobinsonZ**
If you want to host the project via Maven/Gradle/etc [JitPack](https://jitpack.io) does it effortlessly. In fact, it works with the project as it is now! However, I decided to put in a little bit of effort in to make JitPack more seamless–it now generates source and javadoc .jars to make it that much better, and the README is also updated to encourage people to use JitPack with Gradle/Maven.

I also deleted `libs/` because you can, using JitPack, compile json-simple from the [Github mirror](https://github.com/fangyidong/json-simple).

Let me know if you have any questions/improvements.

### CODE REVIEW

**Comment by widavies** [comment]
Thanks!

**Comment by RobinsonZ** [comment]
Quick thing: for this to update with JitPack properly you'll need to create a new release, so I suggest doing that.

**Comment by widavies** [comment]
How do I need to do this? Are you talking about a new .jar to the release page or a release on JitPack's website?

**Comment by RobinsonZ** [comment]
Just a new Github release. I don't even think you need a .jar.

**Pull request merged**
